//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TocToc.ModelData.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProduto
    {
        public TipoProduto()
        {
            this.Produtos = new HashSet<Produto>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Produto> Produtos { get; set; }
    }
}
